######################## default configuration ####################
publishDir = "docs"
# baseURL = "https://link2-guru.github.io/link2.guru/"
baseURL = "link2.guru"
languageCode = "en-us"
title = "LINK2.GURU"
theme = "liva-hugo"
summaryLength = "10"
paginate = 6
disqusShortname = ""

[outputs]
  home = ["HTML", "RSS", "JSON"]
############################# Plugins ##############################
[params.plugins]

  # CSS Plugins
  [[params.plugins.css]]
  URL = "plugins/bootstrap/bootstrap.min.css"
  [[params.plugins.css]]
  URL = "plugins/slick/slick.css"
  [[params.plugins.css]]
  URL = "plugins/themify-icons/themify-icons.css"
  [[params.plugins.css]]
  URL = "plugins/venobox/venobox.css"

  # JS Plugins
  [[params.plugins.js]]
  URL = "plugins/jQuery/jquery.min.js"
  [[params.plugins.js]]
  URL = "plugins/bootstrap/bootstrap.min.js"
  [[params.plugins.js]]
  URL = "plugins/slick/slick.min.js"
  [[params.plugins.js]]
  URL = "plugins/venobox/venobox.min.js"
  [[params.plugins.js]]
  URL = "plugins/search/fuse.min.js"
  [[params.plugins.js]]
  URL = "plugins/search/mark.js"
  [[params.plugins.js]]
  URL = "plugins/search/search.js"


############################## navigation ###############################
[menu]

  # main menu
  [[menu.main]]
  name = "Home"
  URL = "/"
  weight = 1

  [[menu.main]]
  name = "Post"
  URL = "blog"
  weight = 2

  [[menu.main]]
  name = "About"
  URL = "about"
  weight = 3

  [[menu.main]]
  name = "Contact"
  URL = "contact"
  weight = 4

  # footer menu
  [[menu.footer]]
  name = "About"
  URL = "about"
  weight = 1

  [[menu.footer]]
  name = "Post"
  URL = "blog"
  weight = 2

  [[menu.footer]]
  name = "Contact"
  URL = "contact"
  weight = 3


#################### default parameters ################################
[params]
logo = "images/logo.png"
home = "Home"
# Meta data
description = "link2.guru区块链开发团队，专注于公链基础设施，智能合约应用开发，团队成员均来自区块链行业早期的布道者，拥有丰富的开发经验。"

author = ""
# Google Analitycs
googleAnalitycsID = ""
# Contact Information
mobile = ""
email = ""
location = ""
# copyright
copyright = "| copyright &copy; 2020  All Rights Reserved |"

  # Preloader
  [params.preloader]
  enable = true
  preloader = "" # use .png , .svg or .gif format

  # search
  [params.search]
  enable = true

############################ news letter ########################
[params.newsletter]
enable = true
title = "Join Our Newsletter"
content = ""


# cookies
[params.cookies]
enable = true
expire_days = 2


############################# social site ########################
[[params.social]]
title = "facebook"
icon = "ti-facebook" 
link = "#"

[[params.social]]
title = "twitter"
icon = "ti-twitter-alt" 
link = "#"

[[params.social]]
title = "instagram"
icon = "ti-instagram" 
link = "#"

[[params.social]]
title = "github"
icon = "ti-github" 
link = "https://github.com/link2-Guru"

[[params.social]]
title = "linkedin"
icon = "ti-linkedin" 
link = "#"
